[[redirects]]
  from = "/api"
  to = "https://api.mysearch.com"
  status = 200
  force = true
  [redirects.headers]
  #API_SIGNATURE_TOKEN is set from netlfiy console Site settigns -> Build & deploy -> Enviroment
  #and token is written like [Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxx ]
    Authorization= API_SIGNATURE_TOKEN,
    Access-Control-Allow-Origin = '*'